import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Mock Intrervuew",
  description: "Generated by create next appPractice for interviews in a simulated, AI-driven setting to enhance your readiness. Receive instant feedback that helps you fine-tune your answers and improve your performance. With a robust question library, you'll be well-prepared for a variety of interview scenarios, boosting your confidence and chances of success.",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
